name: Test

on:
  pull_request: null
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: "\
          ${{ runner.os }}-stack\
          -${{ hashFiles('**/stack.yaml.lock') }}\
          -${{ hashFiles('**/package.yaml') }}\
        "
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: 9.6.4
        enable-stack: true

    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies

    - name: Run Test
      run: stack --system-ghc test
